name: CI
on:
  - push
jobs:
  job1:
    runs-on: ubuntu-latest
    name: job1
    steps:
    - name: start minikube
      id: minikube
      with:
        driver: none
      uses: evdpronin/OTUS_MVP@k8s-cluster
    # now you can run kubectl to see the pods in the cluster
    - name: kubectl
      run: kubectl get pods -A && minikube ip
