name: CI
on:
  - push
jobs:
  start-minikube:
    runs-on: ubuntu-latest
    steps:
    - name: start minikube
      run: |
        sudo minikube start --driver=none
        sudo minikube addons enable ingress
        sudo minikube addons enable ingress-dns
        sudo minikube addons enable metallb

