name: CI
on:
  - push
jobs:
  start-minikube:
    runs-on: ubuntu-latest
    steps:
    - name: start minikube
      run: |
        minikube start
        minikube addons enable ingress
        minikube addons enable ingress-dns
        minikube addons enable metallb

